### ISSUE TITLE
flac音频解码

### ISSUE THREAD

**Issue by heby** [Baidu-Music-FE/muplayer#82]
http://labs.music.baidu.com/demo/audiolab/?p=5
添加flac音频文件报错，mac chrome 41
![image](https://cloud.githubusercontent.com/assets/3339694/7100999/7d6833ee-e072-11e4-96f8-412db1c6edc7.png)
![image](https://cloud.githubusercontent.com/assets/3339694/7101002/9d2259e4-e072-11e4-9551-7efe27d4ca4c.png)
另外我在github上没找到这个项目地址，没有开源吗？

**Comment by hustKiwi** [comment]
这个项目不是我在维护，是前同事写的一个demo，但是他早就从百度音乐离职了。
网站上demo的代码是未压缩的，你可以参考下：
http://labs.music.baidu.com/demo/audiolab/js/flac/FlacDecoder.js

不过如果需要flac的前端解码，不妨关注下这个项目：
https://github.com/audiocogs/aurora.js
