### ISSUE TITLE
有个问题，关于是否来自缓存

### ISSUE THREAD

**Issue by heby** [Baidu-Music-FE/muplayer#83]
能否暴露一个接口，以确定音频是否来自缓存？
应用场景：
如缓冲进度条，第一次加载可以通过监听progress事件知道缓冲进度，但如果已播放过此歌曲，就会从缓存中加载，而progress事件返回的依然是一个进度值，能否得知是否来自缓存？

**Comment by hustKiwi** [comment]
为什么会需要这样的接口？这个在我们的应用场景中从来没有用到。
另外，progress事件只有在播放时才会派发，即便如你所说，通过progress派发的进度可以估测是否来自缓存，这个方法也不会是可以随意调用的。这种情况下，如果我没有play该音频，调用 `isFromCache` 会得到什么？

我不建议为了一个少见需求暴露接口，所有暴露的接口应该在任何时候都表现一致。基于上述两点，我应该不会添加这个接口，如有需要，可以在你使用时自行扩展一个。
