### ISSUE TITLE
MuPlayer支持IE8浏览器吗？

### ISSUE THREAD

**Issue by mav1s** [Baidu-Music-FE/muplayer#84]
我用IE8访问MuPlayer的demo页面：http://labs.music.baidu.com/demo/muplayer/doc/demo.html

发现页面显示是有问题的。

**Comment by hustKiwi** [comment]
支持IE，页面显示有问题，是因为文档页我没有特意顾及IE的兼容性。不过播放内核本身是可以支持IE的。在不支持Audio标签的浏览器上，会使用Flash的实现方式。现在支持mp3和m4a两种音频资源。

**Comment by mav1s** [comment]
谢谢你的回答，我还有一个疑问：如果我想在 不支持Audio标签的浏览器上能播放wav格式的音频资源，需要额外开发的工作量大不。能提供一下开发的思路吗。

**Comment by hustKiwi** [comment]
@mav1s 当时没有实现，是因为Adobe的ActionScript 3中没有提供wav音频处理的官方库，只有类似 [as3wavsound](https://code.google.com/p/as3wavsound/) 这样的第三方实现，而且看起来也不维护了。

又看了看类似 `jPlayer` 和 `Soundmanager2` 这样的播放开源库，也没有在flash层面对wav做特别处理，因此就没有实现。

我觉得，如果音频资源是你可控的，不妨自己根据需求对音频做一定转码，后端去规避这些前端兼容性问题总是更好的办法。比如通过 `ffmpeg` 去转码：https://trac.ffmpeg.org/wiki/Encode/MP3
