### ISSUE TITLE
如何判断音乐文件加载完成？

### ISSUE THREAD

**Issue by looping84** [Baidu-Music-FE/muplayer#85]
如何判断音乐文件加载完成？

**Comment by hustKiwi** [comment]
监听 `canplaythrough ` 事件就可以知道。不好意思，之前文档中漏写这个事件了，刚刚补充了了一下：
https://github.com/Baidu-Music-FE/muplayer/wiki/%E5%B8%B8%E7%94%A8%E4%BA%8B%E4%BB%B6%E8%AF%B4%E6%98%8E
