### ISSUE TITLE
怎么播放Java的Stream流？

### ISSUE THREAD

**Issue by unknown-coder** [Baidu-Music-FE/muplayer#88]
```html
<ul id="playlist-demo">
    <li data-link="http://localhost:8080/project/getStream.action"><i class="play-btn"></i>音频</li>
</ul>
```

如上，data-link地址返回的是一个application/octet-stream流
貌似播放不了，js直接报错了Uncaught Error: Can not play with: action

**Comment by hustKiwi** [comment]
是的，暂时没有支持流媒体播放。这个报错只是简单通过后缀名判断可以播放的音频类型。但无论如何，现在也还没有支持Stream流，抱歉。
