### ISSUE TITLE
有没有具体如何安装教程，东边要安装一个，西边要安装什么。百度这么大，要是我，用到那个就把他买下来，直到买不起。

### ISSUE THREAD

**Issue by Xia-lj** [Baidu-Music-FE/muplayer#91]
看到一大串英文 就头大。
每次都是介绍个头，然后放个ZIP文件， 同一个源码ZIP，我都下了好几个。

C:\Users\Administrator>npm install -g bower
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by dracupid** [comment]
这位同学应该是刚接触前端。对于有一定经验的前端开发者，node.js，npm甚至bower都是比较常用的工具，项目安装文档通常都不会提及他们的安装方法。如果你只是普通的课程项目或练习，可以不使用bower这样的包管理工具安装，直接下载muplayer的发布版[源代码](https://github.com/Baidu-Music-FE/muplayer/releases)在项目中使用。
你给出的这个问题看日志内容应该是网络连接问题，你可以重试下，使用`npm install -g bower -d`查看更详细的日志信息。

**Comment by Xia-lj** [comment]
是啊，所以很多问题，想问，又不敢说出来， 谢谢 你的建议 对我很有帮助

**Comment by Xia-lj** [comment]
你说的这个 1.0.0版的  我也下载了，能不能用最通俗的方法说一下，我想做个http://labs.music.baidu.com/demo/interactions/visualization/这样的网页，可以加我喜欢的歌曲。

**Comment by Xia-lj** [comment]
http://labs.music.baidu.com/demo/interactions/visualization/

**Comment by Xia-lj** [comment]
d:\nodeme\smjs>npm start

> webAudio@0.0.1 start d:\nodeme\smjs
> node ./bin/www

GET / 304 19ms
GET /javascripts/MusicVisualizer.js 200 99ms - 4.63kb
GET /javascripts/index.js 200 103ms - 5.77kb
GET /stylesheets/index.css 200 116ms - 6.83kb
GET /media/Alexandra%20Stan-Dance.mp3 200 570ms - 3.39mb
GET /media/Avril%20Lavigne-Rock%20N%20Roll.mp3 200 243ms - 3.16mb
------这是我另一个在学的app，似乎本地调试并不复杂---

我安装了 nokit coffee-script 然后 server 文件在哪
所有关于Html5的webAudio 教程看了很多，感觉还差一点点，不知那里没对上，肯定不难。

**Comment by hustKiwi** [comment]
如果不是想介入开发，其实没必要装 `nodejs` 相关的任何依赖的。最简单的办法是下载我们编译并发布的版本，比如[下载这个](https://github.com/Baidu-Music-FE/muplayer/archive/v1.0.0.zip) 在你的项目中引用其中dist目录中的相关文件即可。

另外这个库只是一个音频文件的播放库，可以通过它播放mp3, m4a等音频资源，但它并不是对 WebAudio API的封装，从你的回复中没太理解你想用MuPlayer做什么？

**Comment by hustKiwi** [comment]
如果按上述描述下载下来 MuPlayer 后，你可以在你的项目中类似这个 [demo](http://labs.music.baidu.com/demo/muplayer/doc/demo.html) 一样实现音频资源的播放。具体 MuPlayer 的调用API可以参见：http://labs.music.baidu.com/demo/muplayer/doc/api.html

**Comment by Xia-lj** [comment]
我的工作几乎接触不了什么网页开发。所以我也没什么所谓的项目，我就纯粹的个人兴趣爱好。nodejs 是前面有个 webaudio 需要nodejs ，可以在本地看看。  
闲来折腾网页  不时也有很多乐趣，更是学无止境的字母知识。

这里学学改改 那边研究研究，咦   实现了，会感到一种自我很满足的快乐。呵呵~！  其实就是   “瞎折腾”。  
不饶你费心了，我的问题其实我都说不清。 我自己研究吧，前几天装 bower 怎么也装不上，今天研究过后 装好了。也明白了 bower 是管理我们的包这样一个工作。  
  谢谢 ~！
