### ISSUE TITLE
HTML5不支持mp4(audio)/m4a 有点遗憾 望支持

### ISSUE THREAD

**Issue by StephenKare** [Baidu-Music-FE/muplayer#92]
HTML5不支持mp4(audio)/m4a 有点遗憾 望支持

**Comment by hustKiwi** [comment]
HTML5能否支持m4a是由所用的浏览器决定。 `MuPlayer` 仅仅是调用了浏览器的Audio接口，尝试去播放 m4a等音频，但并不能超越浏览器本身的限制。一般而言，chrome 甚至IE9以上的浏览器应该都可以支持 m4a播放的。
