### ISSUE TITLE
这是MuPlayer的Bug么?很急

### ISSUE THREAD

**Issue by igitinode** [Baidu-Music-FE/muplayer#93]

**Comment by igitinode** [comment]
我的网页用MuPlayer音乐播放,内容很简单,当页面加载完以后就播放指定的音乐,但是在chrome浏览器的手机测试下测试发现,当我随便点击页面的任何地方的时候,音乐就不播放了.这是怎么回事?

**Comment by hustKiwi** [comment]
你这样初始化试试：
```javascript
var player = new _mu.Player({
    engines: [
        {
            constructor: 'AudioCore',
            args: {
                needPlayEmpty: false
            }
        }
    ]
});
```

简单说是为了规避iOS下对Audio标签使用的限制（http://www.ibm.com/developerworks/library/wa-ioshtml5/），我们做了一个hack处理。如果你是非iOS手机，可以通过将 `needPlayEmpty` 设为 false 去掉这个hack。但无论如何，可能都没法让iOS手机打开页面就播放。具体你可以读读我上面链接中的文章。
