### ISSUE TITLE
[求教]声音文件总时长问题？

### ISSUE THREAD

**Issue by chenwfy** [Baidu-Music-FE/muplayer#96]
示例网站：http://www.winsharemusic.com
问题描述：
1、在网络环境比较差的情况下，timeupdate 事件所返回的文件时长muPlayer.duration()不是真实的文件长度，而像是当前缓冲数据的长度？（包括官方示例http://labs.music.baidu.com/demo/muplayer/doc/demo.html上的也是一样的问题）体现在界面上就是当前播放时间和总时长是一样的。
2、同样是网络环境不好时，缓冲数据引起播放暂停，然后再次回复播放时，play 有一定概率不能触发？

**Comment by hustKiwi** [comment]
网站做的不错：）

1. 确实如你所说，在网络情况比较差时，取得的是duration取得的是buffer时长，具体源码见：https://github.com/Baidu-Music-FE/muplayer/blob/master/src/js/core/engines/audioCore.coffee#L245
这个还真没法在前端解决。如果你后端存储曲库时计算了歌曲的总时长，可以尝试覆盖掉这个方法：
https://github.com/Baidu-Music-FE/muplayer/blob/master/src/js/core/engines/engine.coffee#L212
直接返回从后端计算后的时长结果。

2. 这个在我们之前的环境中还没有碰到。而且 `MuPlayer` 是做了一定的卡断后的异常处理和重试的：https://github.com/Baidu-Music-FE/muplayer/blob/master/src/js/player.coffee#L170 ， 感觉你说的不能play是因为数据还没有缓冲到可以play的程度？

另外非常抱歉，虽然我是 `MuPlayer` 的主要开发者，但已经与6月时离开百度音乐了。这个项目后续负责的经理好像不太希望持续维护开源的版本，因此github上的这个项目已经处于停滞状态了。

如果你要开发的是一个非常重要的长期项目，要么了解一下 `MuPlayer` ，可以一同维护更新。要么推荐评估使用一下 [SoundManager2](https://github.com/scottschiller/SoundManager2/)，虽然它的更新也不是那么频繁，但毕竟是用户数众多，还有一定积累。

**Comment by chenwfy** [comment]
@hustKiwi
非常感谢你的回复和建议。。^_^
